version: '3.8'

volumes:
  pgdata:
  static:
  media:

services:

  django:
    build:
      context: .
    ports:
      - '8000:8000'
    container_name: django
    env_file:
      - .env
    volumes:
      - ./:/app
      - static:/app/static
      - media:/app/media
    depends_on:
      - postgres
      - redis
    command: sh -c "poetry config virtualenvs.create true &&
                    python main/manage.py runserver 0.0.0.0:8000"

  postgres:
    image: postgres:17.0-alpine3.20
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=taskuser
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=task_db
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - ./entrypoint.sh:/docker-entrypoint-initdb.d/entrypoint.sh
  
  redis:
    image: redis:7.4.1-alpine3.20
    container_name: redis
    env_file:
      - .env
    expose:
      - 6379
    volumes:
      - ./docker/redis/data:/data
  
  celery-worker:
    build: .
    container_name: celery-worker
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/app
      - media:/app/media
    command: sh -c "cd main &&
                    celery -A main worker --loglevel=INFO"
    depends_on:
      - redis
  
  celery-beat:
      build: .
      container_name: celery-beat
      env_file:
          - .env
      depends_on: 
          - redis
      command: sh -c "cd main &&
                    celery -A main beat --loglevel=INFO"
      volumes:
          - media:/app/media
          - ./:/app