# Generated by Django 5.1.2 on 2024-10-28 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PLANNED', 'PLANNED'), ('ACTIVE', 'ACTIVE'), ('ON_CHECK', 'ON_CHECK'), ('DONE', 'DONE'), ('FAILED', 'FAILED'), ('EXPIRED', 'EXPIRED')], max_length=15)),
                ('time_start', models.DateTimeField(blank=True, null=True)),
                ('time_end', models.DateTimeField(blank=True, null=True)),
                ('time_deadline', models.DateTimeField(blank=True, null=True)),
                ('executor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
                ('observers', models.ManyToManyField(blank=True, related_name='observers', to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, choices=[('PLANNED', 'PLANNED'), ('ACTIVE', 'ACTIVE'), ('ON_CHECK', 'ON_CHECK'), ('DONE', 'DONE'), ('FAILED', 'FAILED'), ('EXPIRED', 'EXPIRED')], max_length=15, null=True)),
                ('next_status', models.CharField(choices=[('PLANNED', 'PLANNED'), ('ACTIVE', 'ACTIVE'), ('ON_CHECK', 'ON_CHECK'), ('DONE', 'DONE'), ('FAILED', 'FAILED'), ('EXPIRED', 'EXPIRED')], default='PLANNED', max_length=15)),
                ('edit_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status_log', to='tasktracker.task')),
            ],
        ),
    ]
