# Generated by Django 5.1.2 on 2024-10-29 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200)),
                ('slug', models.SlugField(default=None, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PLANNED', 'PLANNED'), ('ACTIVE', 'ACTIVE'), ('ON_CHECK', 'ON_CHECK'), ('DONE', 'DONE'), ('FAILED', 'FAILED'), ('EXPIRED', 'EXPIRED')], max_length=15)),
                ('time_start', models.DateTimeField(blank=True, null=True)),
                ('time_end', models.DateTimeField(blank=True, null=True)),
                ('time_deadline', models.DateTimeField(blank=True, null=True)),
                ('executor', models.ManyToManyField(related_name='tasks_as_executor', to=settings.AUTH_USER_MODEL)),
                ('observers', models.ManyToManyField(related_name='tasks_as_observer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, choices=[('PLANNED', 'PLANNED'), ('ACTIVE', 'ACTIVE'), ('ON_CHECK', 'ON_CHECK'), ('DONE', 'DONE'), ('FAILED', 'FAILED'), ('EXPIRED', 'EXPIRED')], max_length=15, null=True)),
                ('next_status', models.CharField(blank=True, choices=[('PLANNED', 'PLANNED'), ('ACTIVE', 'ACTIVE'), ('ON_CHECK', 'ON_CHECK'), ('DONE', 'DONE'), ('FAILED', 'FAILED'), ('EXPIRED', 'EXPIRED')], default='PLANNED', max_length=15, null=True)),
                ('edit_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status_log', to='tasktracker.task')),
            ],
        ),
    ]
