# Generated by Django 5.1.2 on 2024-10-28 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktracker', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='executor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_as_executor', to='user.user'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='observers',
        ),
        migrations.AddField(
            model_name='task',
            name='observers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_as_observer', to='user.user'),
        ),
    ]
