# Generated by Django 5.1.2 on 2024-10-30 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasktracker', '0002_alter_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='next_status',
            new_name='set_status',
        ),
    ]
