# Generated by Django 5.1.2 on 2024-10-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktracker', '0003_remove_task_executor_remove_task_observers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='slug',
            field=models.SlugField(default=None, unique=True),
        ),
    ]
