# Generated by Django 5.1.2 on 2024-11-05 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktracker', '0003_rename_next_status_status_set_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='executor',
            field=models.ManyToManyField(blank=True, related_name='tasks_as_executor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='observers',
            field=models.ManyToManyField(blank=True, related_name='tasks_as_observer', to=settings.AUTH_USER_MODEL),
        ),
    ]
