# Generated by Django 5.1.2 on 2024-10-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktracker', '0004_task_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=models.SlugField(default=None, null=True, unique=True),
        ),
    ]
