# Generated by Django 5.1.2 on 2024-10-28 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasktracker', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('CREATED', 'CREATED'), ('UPDATED', 'UPDATED'), ('DELETED', 'DELETED'), ('REMIND', 'REMIND')], max_length=10)),
                ('recipient_list', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recipient', to='user.user')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='tasktracker.task')),
            ],
        ),
    ]
