# Generated by Django 5.1.2 on 2024-10-30 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('tasktracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='tasktracker.task'),
        ),
    ]
