# Generated by Django 5.1.2 on 2024-10-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='recipient_list',
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient_list',
            field=models.ManyToManyField(related_name='recipient', to='user.user'),
        ),
    ]
