# Generated by Django 5.1.2 on 2024-10-30 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='event_type',
        ),
    ]
